name: Dev-build

on:
  pull_request:
    branches:
    - main

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build and Test Web App
    environment: Dev
    runs-on: ubuntu-latest
    env:
      CONFIGURATION: Release
      NODE_VERSION: '18.x'

    steps:
      - uses: actions/checkout@v3

      - name: npm install and build
        run: |
          npm install --legacy-peer-deps
          npm run build:dev --if-present

        env:
          CI: false
          
